// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMOKTW4ks5fa9GX8x9y2miDWWTtGNeyco',
    appId: '1:1008258013681:web:73d04e63326dc202a90c50',
    messagingSenderId: '1008258013681',
    projectId: 'vetsync-a6216',
    authDomain: 'vetsync-a6216.firebaseapp.com',
    storageBucket: 'vetsync-a6216.firebasestorage.app',
    measurementId: 'G-4JMK15FSFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ0-1BFTER8-1PUYwBXjW-3mBpEK2_zto',
    appId: '1:1008258013681:android:3ff84802da5797bfa90c50',
    messagingSenderId: '1008258013681',
    projectId: 'vetsync-a6216',
    storageBucket: 'vetsync-a6216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmjqf9GkqzQVoIqPUYgRlBdSj8pv55Djk',
    appId: '1:1008258013681:ios:97f83b5ae1738909a90c50',
    messagingSenderId: '1008258013681',
    projectId: 'vetsync-a6216',
    storageBucket: 'vetsync-a6216.firebasestorage.app',
    iosBundleId: 'com.example.vetsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmjqf9GkqzQVoIqPUYgRlBdSj8pv55Djk',
    appId: '1:1008258013681:ios:97f83b5ae1738909a90c50',
    messagingSenderId: '1008258013681',
    projectId: 'vetsync-a6216',
    storageBucket: 'vetsync-a6216.firebasestorage.app',
    iosBundleId: 'com.example.vetsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMOKTW4ks5fa9GX8x9y2miDWWTtGNeyco',
    appId: '1:1008258013681:web:94f29d87e6eb69d4a90c50',
    messagingSenderId: '1008258013681',
    projectId: 'vetsync-a6216',
    authDomain: 'vetsync-a6216.firebaseapp.com',
    storageBucket: 'vetsync-a6216.firebasestorage.app',
    measurementId: 'G-CS8DBN89H0',
  );
}
